LOAD DATA local inpath '/textfiles/customer_data.txt' overwrite INTO TABLE dim_customer;
LOAD DATA local inpath '/textfiles/employee_data.txt' overwrite INTO TABLE dim_employee;
LOAD DATA local inpath '/textfiles/main_technology_data.txt' overwrite INTO TABLE dim_main_technology;
LOAD DATA local inpath '/textfiles/sprint_retrospective_data.txt' overwrite INTO TABLE dim_sprint_retrospective;
LOAD DATA local inpath '/textfiles/team_data.txt' overwrite INTO TABLE dim_team;
LOAD DATA local inpath '/textfiles/time_data.txt' overwrite INTO TABLE dim_time;
LOAD DATA local inpath '/textfiles/project_fact_data.txt' overwrite INTO TABLE fact_project;
LOAD DATA local inpath '/textfiles/sprint_fact_data.txt' overwrite INTO TABLE fact_sprint;
LOAD DATA local inpath '/textfiles/task_fact_data.txt' overwrite INTO TABLE fact_task;
